apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot-sample
  name: springboot-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-sample
    spec:
      containers:
      - image: springboot-sample
        name: springboot-sample
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        imagePullPolicy: IfNotPresent
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot-sample
  name: springboot-sample
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-sample
  type: LoadBalancer
status:
  loadBalancer: {}
